name: CI Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  lint:
    name: Lint & Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-project
        with:
          node-version: '18'
      - run: npm run lint
      # Make Prettier warnings non-blocking
      - run: npm run format:check || echo "⚠️ Prettier found formatting issues, but continuing..."

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-project
        with:
          node-version: '18'

      - name: Run tests with coverage
        run: npm test -- --config=jest.config.cjs

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Fail if coverage < 80%
        run: |
          COVERAGE=$(node -p "require('./coverage/coverage-summary.json').total.lines.pct")
          echo "Coverage: $COVERAGE%"
          if (( $(echo "$COVERAGE < 80" | bc -l) )); then
            echo "❌ Coverage is below 80%"
            exit 1
          else
            echo "✅ Coverage is sufficient"
          fi

  build:
    name: Build & Artifact
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-project
        with:
          node-version: '18'
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: site-dist
          path: dist/
          retention-days: 7
